import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import dts from 'vite-plugin-dts'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    dts({
      outDir: './dist/types',
      // https://stackoverflow.com/a/78825198/10351342
      tsconfigPath: './tsconfig.app.json',
    }),
  ],
  build: {
    outDir: './dist',
    lib: {
      entry: './src/index.ts',
      name: 'ui-utils',
      formats: ['es'],
      fileName: (format) => `ui-utils.${format}.js`,
    },
    rollupOptions: {
      // external modules won't be bundled into your library
      external: ['vue', 'vuetify'],
    },
    emptyOutDir: false, // to retain the types folder generated by tsc
  },
})
